### ISSUE TITLE
Should [Users] be [User]

### ISSUE THREAD

**Issue by zol** [sogko/graphql-shorthand-notation-cheat-sheet#1]
I'm learning GQL and am confused by the example below. Wondering if it's a typo and the line should read:

`users(params: ListUsersInput): [User]!`

![image](https://cloud.githubusercontent.com/assets/81672/15956462/083c44ac-2f2c-11e6-9b3b-707a9f52efb6.png)

**Comment by sogko** [comment]
Hi @zol 

Nice catch! Yeap, you're right, that's a typo!

I'll fix it soon, thanks!

Cheers 👍

**Comment by sogko** [comment]
Fixed! Thanks @zol

**Comment by zol** [comment]
Awesome, thanks! (that was fassstt)
